In [36]:
import pandas as pd

In [37]:
df = pd.read_csv('各鄉鎮市區人口密度.csv')
print(df.info)

<bound method DataFrame.info of     statistic_yyy                                            site_id  \
0             統計年                                                區域別
1             106                                             新北市板橋區
2             106                                             新北市三重區
3             106                                             新北市中和區
4             106                                             新北市永和區
..            ...                                                ...
371           NaN                                                NaN
372           NaN                           說明：1.人口密度係指每單位土地面積內之人口數。
373           NaN  2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里)
374           NaN           ，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。
375           NaN           3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。

    people_total     area population_density
0          年底人口數     土地面積               人口密度
1         551480  23.1373              23835
2         387484   16.317              23747
3         413590   20.144              20532
4         222585   5.7138              38956
..           ...      ...                ...
371          NaN      NaN                NaN
372          NaN      NaN                NaN
373          NaN      NaN                NaN
374          NaN      NaN                NaN
375          NaN      NaN                NaN

[376 rows x 5 columns]>

In [38]:
df = pd.read_csv('各鄉鎮市區人口密度.csv', skiprows=1)
print(df.info)
print(df.columns)

<bound method DataFrame.info of        統計年                                                區域別   年底人口數  \
0    106.0                                             新北市板橋區  551480
1    106.0                                             新北市三重區  387484
2    106.0                                             新北市中和區  413590
3    106.0                                             新北市永和區  222585
4    106.0                                             新北市新莊區  416524
..     ...                                                ...     ...
370    NaN                                                NaN     NaN
371    NaN                           說明：1.人口密度係指每單位土地面積內之人口數。     NaN
372    NaN  2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里)     NaN
373    NaN           ，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。     NaN
374    NaN           3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。     NaN

        土地面積   人口密度
0    23.1373  23835
1    16.3170  23747
2    20.1440  20532
3     5.7138  38956
4    19.7383  21102
..       ...    ...
370      NaN    NaN
371      NaN    NaN
372      NaN    NaN
373      NaN    NaN
374      NaN    NaN

[375 rows x 5 columns]>
Index(['統計年', '區域別', '年底人口數', '土地面積', '人口密度'], dtype='object')

In [39]:
df.columns = ['year', 'district', 'population', 'area', 'density']
print(df.tail(3))
print(df.shape)

     year                                           district population  area  \
372   NaN  2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里)        NaN   NaN
373   NaN           ，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。        NaN   NaN
374   NaN           3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。        NaN   NaN

    density
372     NaN
373     NaN
374     NaN
(375, 5)

In [40]:
df1 = df.dropna(axis=0, how='any')
print(df1.head(3))
print(df1.tail(3))
print(df1.shape)

    year district population     area density
0  106.0   新北市板橋區     551480  23.1373   23835
1  106.0   新北市三重區     387484  16.3170   23747
2  106.0   新北市中和區     413590  20.1440   20532
      year district population    area density
365  106.0   連江縣北竿鄉       2360  9.9000     238
368  106.0     東沙群島         …   2.3800      …
369  106.0     南沙群島         …   0.5045      …
(364, 5)

In [41]:
df2 = df1.drop('year', axis=1)
print(df2.head(5))
print(df2.info())

  district population     area density
0   新北市板橋區     551480  23.1373   23835
1   新北市三重區     387484  16.3170   23747
2   新北市中和區     413590  20.1440   20532
3   新北市永和區     222585   5.7138   38956
4   新北市新莊區     416524  19.7383   21102
<class 'pandas.core.frame.DataFrame'>
Index: 364 entries, 0 to 369
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   district    364 non-null    object
 1   population  364 non-null    object
 2   area        364 non-null    float64
 3   density     364 non-null    object
dtypes: float64(1), object(3)
memory usage: 14.2+ KB
None

In [42]:
print(df2.nunique())
unique_values = df2.apply(lambda x: x.unique())
print(unique_values)

district      364
population    363
area          363
density       331
dtype: int64
district      [新北市板橋區, 新北市三重區, 新北市中和區, 新北市永和區, 新北市新莊區, 新北市新店...
population    [551480, 387484, 413590, 222585, 416524, 30208...
area          [23.1373, 16.317, 20.144, 5.7138, 19.7383, 120...
density       [23835, 23747, 20532, 38956, 21102, 2513, 5559...
dtype: object

In [43]:
def find_duplicate(df:pd.DataFrame, col_names:str):
    counts = df.groupby(col_names).size()
    dup_values = counts[counts > 1].index
    duplicates = df[df[col_names].isin(dup_values)]
    print(duplicates)

# find_duplicate(df2, 'population')
# find_duplicate(df2, 'area')
# find_duplicate(df2, 'density')

# col_names = [col for i, col in enumerate(df.columns) if i != 2]
# print(col_names)

# for i in range(len(col_names)):
    # col = col_names[i]
    # print(col)
    # find_duplicate(df2, 'population')

def  str2int(x):
    try:
        return int(x)
    except:
        return 0


df2['population'] = df2['population'].apply(str2int)
df2['density'] = df2['density'].apply(str2int)
df2['density'] = df2['density'].astype('float')
print(df2.info())
print(df2.head(2))

<class 'pandas.core.frame.DataFrame'>
Index: 364 entries, 0 to 369
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   district    364 non-null    object
 1   population  364 non-null    int64
 2   area        364 non-null    float64
 3   density     364 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 14.2+ KB
None
  district  population     area  density
0   新北市板橋區      551480  23.1373  23835.0
1   新北市三重區      387484  16.3170  23747.0

In [44]:
def get_city(v:str)->str:
    if(len(v) >= 6):
        return v[:3]
    else:
        return v
    
def get_district(v:str)->str:
    if(len(v) >= 6):
        return v[-3:]
    else:
        return v
    
# print(df2['district'].apply(get_city))
# print(df2['district'].apply(get_district))

df3 = df2
df3['city'] = df3['district'].apply(get_city)
df3['district'] = df3['district'].apply(get_district)
print(df3.head(3))

df3 = df3.reindex(columns = ['city', 'district', 'population', 'area', 'density'])
print(df3.head(3))

  district  population     area  density city
0      板橋區      551480  23.1373  23835.0  新北市
1      三重區      387484  16.3170  23747.0  新北市
2      中和區      413590  20.1440  20532.0  新北市
  city district  population     area  density
0  新北市      板橋區      551480  23.1373  23835.0
1  新北市      三重區      387484  16.3170  23747.0
2  新北市      中和區      413590  20.1440  20532.0

In [ ]:
print(df3.query('population >= 500000'))

pup_max = df3['population'].max()
print(pup_max)

df3.query('population == @pup_max')

  city district  population     area  density
0  新北市      板橋區      551480  23.1373  23835.0
551480

  city district  population     area  density
0  新北市      板橋區      551480  23.1373  23835.0

In [56]:
# calculate sum, mean, std for city's population, area, and density
df4 = df3

# df4.groupby(by='city')[['population', 'area', 'density']].mean()
df4_agg = df4.groupby(by='city')[['population', 'area', 'density']].agg(['sum', 'mean', 'std'])
print(df4_agg.head(3))

print(df4_agg.columns)
print(df4_agg.columns.names)

df4_agg.columns.names = ["data", "statistics"]
print(df4_agg.head(3))

      population                                    area              \
             sum           mean           std        sum        mean
city
南投縣       501051   38542.384615  33541.229687  4106.4360  315.879692
南沙群島           0       0.000000           NaN     0.5045    0.504500
嘉義市東區     122103  122103.000000           NaN    30.1556   30.155600

                  density
              std     sum         mean         std
city
南投縣    461.834751  4403.0   338.692308  408.226731
南沙群島          NaN     0.0     0.000000         NaN
嘉義市東區         NaN  4049.0  4049.000000         NaN
MultiIndex([('population',  'sum'),
            ('population', 'mean'),
            ('population',  'std'),
            (      'area',  'sum'),
            (      'area', 'mean'),
            (      'area',  'std'),
            (   'density',  'sum'),
            (   'density', 'mean'),
            (   'density',  'std')],
           )
[None, None]
data       population                                    area              \
statistics        sum           mean           std        sum        mean
city
南投縣            501051   38542.384615  33541.229687  4106.4360  315.879692
南沙群島                0       0.000000           NaN     0.5045    0.504500
嘉義市東區          122103  122103.000000           NaN    30.1556   30.155600

data                   density
statistics         std     sum         mean         std
city
南投縣         461.834751  4403.0   338.692308  408.226731
南沙群島               NaN     0.0     0.000000         NaN
嘉義市東區              NaN  4049.0  4049.000000         NaN

In [57]:
# turn into wide dataset
df5 = df4_agg

df5.stack(level=['data', 'statistics'], future_stack=True).unstack(level=['city', 'data'])

city                  南投縣                                 南沙群島          \
data           population         area      density population    area
statistics
sum         501051.000000  4106.436000  4403.000000        0.0  0.5045
mean         38542.384615   315.879692   338.692308        0.0  0.5045
std          33541.229687   461.834751   408.226731        NaN     NaN

city                    嘉義市東區                       嘉義市西區  ...         連江縣  \
data       density population     area density population  ...     density
statistics                                                 ...
sum            0.0   122103.0  30.1556  4049.0   147295.0  ...  963.000000
mean           0.0   122103.0  30.1556  4049.0   147295.0  ...  481.500000
std            NaN        NaN      NaN     NaN        NaN  ...  344.361002

city                  金門縣                                     雲林縣  \
data           population        area      density     population
statistics
sum         137456.000000  151.656000  5596.000000  690373.000000
mean         22909.333333   25.276000   932.666667   34518.650000
std          14994.119950   15.634367   552.526078   22009.465486

city                                            高雄市               \
data               area       density    population         area
statistics
sum         1290.832600  11201.000000  2.776912e+06  2951.852400
mean          64.541630    560.050000  7.307663e+04    77.680326
std           28.839893    283.601179  8.749922e+04   153.403744

city
data              density
statistics
sum         194410.000000
mean          5116.052632
std           7136.503110

[3 rows x 105 columns]