In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('taiwan.csv')
# display(df)
df.head(3)

,國家,ID,iso_code,洲名,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
0,台灣,163987,TWN,亞洲,2020-01-16,0,0,0.0,0,0,...,0.0,0.0,0.0,8.33,23855008,42.2,8.353,80.46,0,99999.0
1,台灣,163988,TWN,亞洲,2020-01-17,0,0,0.0,0,0,...,0.0,0.0,0.0,8.33,23855008,42.2,8.353,80.46,0,99999.0
2,台灣,163989,TWN,亞洲,2020-01-18,0,0,0.0,0,0,...,0.0,0.0,0.0,8.33,23855008,42.2,8.353,80.46,0,99999.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 903 entries, 0 to 902
Data columns (total 33 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   國家              903 non-null    object
 1   ID              903 non-null    int64
 2   iso_code        903 non-null    object
 3   洲名              903 non-null    object
 4   日期              903 non-null    object
 5   總確診數            903 non-null    int64
 6   新增確診數           903 non-null    int64
 7   七天移動平均新增確診數     903 non-null    float64
 8   總死亡數            903 non-null    int64
 9   新增死亡數           903 non-null    int64
 10  七天移動平均新增死亡數     903 non-null    float64
 11  每百萬人確診數         903 non-null    float64
 12  每百萬人死亡數         903 non-null    float64
 13  傳染率             903 non-null    float64
 14  新增檢驗件數          903 non-null    int64
 15  總檢驗件數           903 non-null    int64
 16  每千人檢驗件數         903 non-null    float64
 17  七天移動平均新增檢驗件數    903 non-null    float64
 18  陽性率             903 non-null    float64
 19  每確診案例相對檢驗數量     903 non-null    float64
 20  疫苗總接種總劑數        903 non-null    int64
 21  疫苗總接種人數         903 non-null    int64
 22  疫苗新增接種劑數        903 non-null    int64
 23  七天移動平均疫苗新增接種劑數  903 non-null    float64
 24  每百人接種疫苗劑數       903 non-null    float64
 25  每百人接種疫苗人數       903 non-null    float64
 26  疫情控管指數          903 non-null    float64
 27  總人口數            903 non-null    int64
 28  中位數年紀           903 non-null    float64
 29  70歲以上人口比例       903 non-null    float64
 30  平均壽命            903 non-null    float64
 31  解除隔離數           903 non-null    int64
 32  解封指數            903 non-null    float64
dtypes: float64(17), int64(12), object(4)
memory usage: 232.9+ KB

In [40]:
# df.iloc[row,column] # index
# df.loc[row,column] # name
print(df.iloc[:5, [0,4,6]])

print(df.loc[:5,["國家", "日期", "總確診數"]])

   國家          日期  新增確診數
0  台灣  2020-01-16      0
1  台灣  2020-01-17      0
2  台灣  2020-01-18      0
3  台灣  2020-01-19      0
4  台灣  2020-01-20      0
   國家          日期  總確診數
0  台灣  2020-01-16     0
1  台灣  2020-01-17     0
2  台灣  2020-01-18     0
3  台灣  2020-01-19     0
4  台灣  2020-01-20     0
5  台灣  2020-01-21     0

In [41]:
print(df.iloc[:3])

df1 = df[df['新增確診數'] >= 12]
print(df.iloc[:3])

   國家      ID iso_code  洲名          日期  總確診數  新增確診數  七天移動平均新增確診數  總死亡數  新增死亡數  \
0  台灣  163987      TWN  亞洲  2020-01-16     0      0          0.0     0      0
1  台灣  163988      TWN  亞洲  2020-01-17     0      0          0.0     0      0
2  台灣  163989      TWN  亞洲  2020-01-18     0      0          0.0     0      0

   ...  七天移動平均疫苗新增接種劑數  每百人接種疫苗劑數  每百人接種疫苗人數  疫情控管指數      總人口數  中位數年紀  \
0  ...             0.0        0.0        0.0    8.33  23855008   42.2
1  ...             0.0        0.0        0.0    8.33  23855008   42.2
2  ...             0.0        0.0        0.0    8.33  23855008   42.2

   70歲以上人口比例   平均壽命  解除隔離數     解封指數
0      8.353  80.46      0  99999.0
1      8.353  80.46      0  99999.0
2      8.353  80.46      0  99999.0

[3 rows x 33 columns]
   國家      ID iso_code  洲名          日期  總確診數  新增確診數  七天移動平均新增確診數  總死亡數  新增死亡數  \
0  台灣  163987      TWN  亞洲  2020-01-16     0      0          0.0     0      0
1  台灣  163988      TWN  亞洲  2020-01-17     0      0          0.0     0      0
2  台灣  163989      TWN  亞洲  2020-01-18     0      0          0.0     0      0

   ...  七天移動平均疫苗新增接種劑數  每百人接種疫苗劑數  每百人接種疫苗人數  疫情控管指數      總人口數  中位數年紀  \
0  ...             0.0        0.0        0.0    8.33  23855008   42.2
1  ...             0.0        0.0        0.0    8.33  23855008   42.2
2  ...             0.0        0.0        0.0    8.33  23855008   42.2

   70歲以上人口比例   平均壽命  解除隔離數     解封指數
0      8.353  80.46      0  99999.0
1      8.353  80.46      0  99999.0
2      8.353  80.46      0  99999.0

[3 rows x 33 columns]

In [42]:
# only ascii charater can compare 
print(df['日期'] <= "2020-01-20")

condition = (df['日期'] > "2020-01-20") & (df['日期'] <= "2020-01-31")
df2 = df[condition]
print(df2.iloc[:3,])

0       True
1       True
2       True
3       True
4       True
       ...
898    False
899    False
900    False
901    False
902    False
Name: 日期, Length: 903, dtype: bool
   國家      ID iso_code  洲名          日期  總確診數  新增確診數  七天移動平均新增確診數  總死亡數  新增死亡數  \
5  台灣  163992      TWN  亞洲  2020-01-21     0      0          0.0     0      0
6  台灣  163993      TWN  亞洲  2020-01-22     1      0          0.0     0      0
7  台灣  163994      TWN  亞洲  2020-01-23     1      0          0.0     0      0

   ...  七天移動平均疫苗新增接種劑數  每百人接種疫苗劑數  每百人接種疫苗人數  疫情控管指數      總人口數  中位數年紀  \
5  ...             0.0        0.0        0.0   13.89  23855008   42.2
6  ...             0.0        0.0        0.0   13.89  23855008   42.2
7  ...             0.0        0.0        0.0   19.44  23855008   42.2

   70歲以上人口比例   平均壽命  解除隔離數     解封指數
5      8.353  80.46      0  99999.0
6      8.353  80.46      0  99999.0
7      8.353  80.46      0  99999.0

[3 rows x 33 columns]

In [43]:
# another way
df.query('日期 >= "2020-01-20" and 日期 < "2020-02-01" and 新增確診數 >= 3')

,國家,ID,iso_code,洲名,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
12,台灣,163999,TWN,亞洲,2020-01-28,8,3,1.0,0,0,...,0.0,0.0,0.0,19.44,23855008,42.2,8.353,80.46,0,99999.0

In [54]:
pd.to_datetime(df['日期']).dtype

df['date'] = pd.to_datetime(df['日期'])
df.info()

print(df.query('date in "2020/01/16"'))
print(df.query('date == "2020/01/16"'))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 903 entries, 0 to 902
Data columns (total 34 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   國家              903 non-null    object
 1   ID              903 non-null    int64
 2   iso_code        903 non-null    object
 3   洲名              903 non-null    object
 4   日期              903 non-null    object
 5   總確診數            903 non-null    int64
 6   新增確診數           903 non-null    int64
 7   七天移動平均新增確診數     903 non-null    float64
 8   總死亡數            903 non-null    int64
 9   新增死亡數           903 non-null    int64
 10  七天移動平均新增死亡數     903 non-null    float64
 11  每百萬人確診數         903 non-null    float64
 12  每百萬人死亡數         903 non-null    float64
 13  傳染率             903 non-null    float64
 14  新增檢驗件數          903 non-null    int64
 15  總檢驗件數           903 non-null    int64
 16  每千人檢驗件數         903 non-null    float64
 17  七天移動平均新增檢驗件數    903 non-null    float64
 18  陽性率             903 non-null    float64
 19  每確診案例相對檢驗數量     903 non-null    float64
 20  疫苗總接種總劑數        903 non-null    int64
 21  疫苗總接種人數         903 non-null    int64
 22  疫苗新增接種劑數        903 non-null    int64
 23  七天移動平均疫苗新增接種劑數  903 non-null    float64
 24  每百人接種疫苗劑數       903 non-null    float64
 25  每百人接種疫苗人數       903 non-null    float64
 26  疫情控管指數          903 non-null    float64
 27  總人口數            903 non-null    int64
 28  中位數年紀           903 non-null    float64
 29  70歲以上人口比例       903 non-null    float64
 30  平均壽命            903 non-null    float64
 31  解除隔離數           903 non-null    int64
 32  解封指數            903 non-null    float64
 33  date            903 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(17), int64(12), object(4)
memory usage: 240.0+ KB
   國家      ID iso_code  洲名          日期  總確診數  新增確診數  七天移動平均新增確診數  總死亡數  新增死亡數  \
0  台灣  163987      TWN  亞洲  2020-01-16     0      0          0.0     0      0

   ...  每百人接種疫苗劑數  每百人接種疫苗人數  疫情控管指數      總人口數  中位數年紀  70歲以上人口比例   平均壽命  \
0  ...        0.0        0.0    8.33  23855008   42.2      8.353  80.46

   解除隔離數     解封指數       date
0      0  99999.0 2020-01-16

[1 rows x 34 columns]
   國家      ID iso_code  洲名          日期  總確診數  新增確診數  七天移動平均新增確診數  總死亡數  新增死亡數  \
0  台灣  163987      TWN  亞洲  2020-01-16     0      0          0.0     0      0

   ...  每百人接種疫苗劑數  每百人接種疫苗人數  疫情控管指數      總人口數  中位數年紀  70歲以上人口比例   平均壽命  \
0  ...        0.0        0.0    8.33  23855008   42.2      8.353  80.46

   解除隔離數     解封指數       date
0      0  99999.0 2020-01-16

[1 rows x 34 columns]

C:\Users\s0983\AppData\Local\Temp\ipykernel_21912\3088418743.py:6: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  print(df.query('date in "2020/01/16"'))
C:\Users\s0983\AppData\Local\Temp\ipykernel_21912\3088418743.py:7: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  print(df.query('date == "2020/01/16"'))

In [57]:
df3 = df.set_index('date')
df3.head(3)

,國家,ID,iso_code,洲名,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
date,,,,,,,,,,,,,,,,,,,,,
2020-01-16,台灣,163987,TWN,亞洲,2020-01-16,0,0,0.0,0,0,...,0.0,0.0,0.0,8.33,23855008,42.2,8.353,80.46,0,99999.0
2020-01-17,台灣,163988,TWN,亞洲,2020-01-17,0,0,0.0,0,0,...,0.0,0.0,0.0,8.33,23855008,42.2,8.353,80.46,0,99999.0
2020-01-18,台灣,163989,TWN,亞洲,2020-01-18,0,0,0.0,0,0,...,0.0,0.0,0.0,8.33,23855008,42.2,8.353,80.46,0,99999.0

In [64]:
print(df3.loc['2020-02'])
print(df3.loc['2020-01':'2020-02'])

            國家      ID iso_code  洲名          日期  總確診數  新增確診數  七天移動平均新增確診數  \
date
2020-02-01  台灣  164003      TWN  亞洲  2020-02-01    10      0        1.000
2020-02-02  台灣  164004      TWN  亞洲  2020-02-02    10      0        0.857
2020-02-03  台灣  164005      TWN  亞洲  2020-02-03    10      0        0.714
2020-02-04  台灣  164006      TWN  亞洲  2020-02-04    11      1        0.429
2020-02-05  台灣  164007      TWN  亞洲  2020-02-05    11      0        0.429
2020-02-06  台灣  164008      TWN  亞洲  2020-02-06    16      5        1.000
2020-02-07  台灣  164009      TWN  亞洲  2020-02-07    16      0        0.857
2020-02-08  台灣  164010      TWN  亞洲  2020-02-08    17      1        1.000
2020-02-09  台灣  164011      TWN  亞洲  2020-02-09    18      1        1.143
2020-02-10  台灣  164012      TWN  亞洲  2020-02-10    18      0        1.143
2020-02-11  台灣  164013      TWN  亞洲  2020-02-11    18      0        1.000
2020-02-12  台灣  164014      TWN  亞洲  2020-02-12    18      0        1.000
2020-02-13  台灣  164015      TWN  亞洲  2020-02-13    18      0        0.286
2020-02-14  台灣  164016      TWN  亞洲  2020-02-14    18      0        0.286
2020-02-15  台灣  164017      TWN  亞洲  2020-02-15    18      0        0.143
2020-02-16  台灣  164018      TWN  亞洲  2020-02-16    20      2        0.286
2020-02-17  台灣  164019      TWN  亞洲  2020-02-17    22      2        0.571
2020-02-18  台灣  164020      TWN  亞洲  2020-02-18    22      0        0.571
2020-02-19  台灣  164021      TWN  亞洲  2020-02-19    23      1        0.714
2020-02-20  台灣  164022      TWN  亞洲  2020-02-20    24      1        0.857
2020-02-21  台灣  164023      TWN  亞洲  2020-02-21    26      2        1.143
2020-02-22  台灣  164024      TWN  亞洲  2020-02-22    26      0        1.143
2020-02-23  台灣  164025      TWN  亞洲  2020-02-23    28      2        1.143
2020-02-24  台灣  164026      TWN  亞洲  2020-02-24    30      2        1.143
2020-02-25  台灣  164027      TWN  亞洲  2020-02-25    31      1        1.286
2020-02-26  台灣  164028      TWN  亞洲  2020-02-26    32      1        1.286
2020-02-27  台灣  164029      TWN  亞洲  2020-02-27    32      0        1.143
2020-02-28  台灣  164030      TWN  亞洲  2020-02-28    34      2        1.143
2020-02-29  台灣  164031      TWN  亞洲  2020-02-29    39      5        1.857

            總死亡數  新增死亡數  ...  七天移動平均疫苗新增接種劑數  每百人接種疫苗劑數  每百人接種疫苗人數  疫情控管指數  \
date                     ...
2020-02-01     0      0  ...             0.0        0.0        0.0   19.44
2020-02-02     0      0  ...             0.0        0.0        0.0   30.56
2020-02-03     0      0  ...             0.0        0.0        0.0   30.56
2020-02-04     0      0  ...             0.0        0.0        0.0   30.56
2020-02-05     0      0  ...             0.0        0.0        0.0   30.56
2020-02-06     0      0  ...             0.0        0.0        0.0   30.56
2020-02-07     0      0  ...             0.0        0.0        0.0   30.56
2020-02-08     0      0  ...             0.0        0.0        0.0   30.56
2020-02-09     0      0  ...             0.0        0.0        0.0   30.56
2020-02-10     0      0  ...             0.0        0.0        0.0   30.56
2020-02-11     0      0  ...             0.0        0.0        0.0   30.56
2020-02-12     0      0  ...             0.0        0.0        0.0   30.56
2020-02-13     0      0  ...             0.0        0.0        0.0   30.56
2020-02-14     0      0  ...             0.0        0.0        0.0   30.56
2020-02-15     0      0  ...             0.0        0.0        0.0   30.56
2020-02-16     1      1  ...             0.0        0.0        0.0   30.56
2020-02-17     1      0  ...             0.0        0.0        0.0   30.56
2020-02-18     1      0  ...             0.0        0.0        0.0   30.56
2020-02-19     1      0  ...             0.0        0.0        0.0   30.56
2020-02-20     1      0  ...             0.0        0.0        0.0   30.56
2020-02-21     1      0  ...             0.0        0.0        0.0   30.56
2020-02-22     1      0  ...             0.0        0.0        0.0   30.56
2020-02-23     1      0  ...             0.0        0.0        0.0   30.56
2020-02-24     1      0  ...             0.0        0.0        0.0   30.56
2020-02-25     1      0  ...             0.0        0.0        0.0   23.15
2020-02-26     1      0  ...             0.0        0.0        0.0   23.15
2020-02-27     1      0  ...             0.0        0.0        0.0   23.15
2020-02-28     1      0  ...             0.0        0.0        0.0   23.15
2020-02-29     1      0  ...             0.0        0.0        0.0   23.15

                總人口數  中位數年紀  70歲以上人口比例   平均壽命  解除隔離數      解封指數
date
2020-02-01  23855008   42.2      8.353  80.46      0  99999.00
2020-02-02  23855008   42.2      8.353  80.46      0  99999.00
2020-02-03  23855008   42.2      8.353  80.46      0  99999.00
2020-02-04  23855008   42.2      8.353  80.46      0  99999.00
2020-02-05  23855008   42.2      8.353  80.46      0  99999.00
2020-02-06  23855008   42.2      8.353  80.46      1  99999.00
2020-02-07  23855008   42.2      8.353  80.46      1  99999.00
2020-02-08  23855008   42.2      8.353  80.46      1  99999.00
2020-02-09  23855008   42.2      8.353  80.46      1  99999.00
2020-02-10  23855008   42.2      8.353  80.46      1  99999.00
2020-02-11  23855008   42.2      8.353  80.46      1  99999.00
2020-02-12  23855008   42.2      8.353  80.46      1  99999.00
2020-02-13  23855008   42.2      8.353  80.46      1  99999.00
2020-02-14  23855008   42.2      8.353  80.46      2  99999.00
2020-02-15  23855008   42.2      8.353  80.46      2  99999.00
2020-02-16  23855008   42.2      8.353  80.46      2      9.53
2020-02-17  23855008   42.2      8.353  80.46      2     10.52
2020-02-18  23855008   42.2      8.353  80.46      2     10.52
2020-02-19  23855008   42.2      8.353  80.46      2     11.02
2020-02-20  23855008   42.2      8.353  80.46      2     11.52
2020-02-21  23855008   42.2      8.353  80.46      2     12.52
2020-02-22  23855008   42.2      8.353  80.46      2     12.52
2020-02-23  23855008   42.2      8.353  80.46      2     13.52
2020-02-24  23855008   42.2      8.353  80.46      5      5.21
2020-02-25  23855008   42.2      8.353  80.46      5      5.41
2020-02-26  23855008   42.2      8.353  80.46      5      5.61
2020-02-27  23855008   42.2      8.353  80.46      5      5.61
2020-02-28  23855008   42.2      8.353  80.46      6      4.84
2020-02-29  23855008   42.2      8.353  80.46      9      3.45

[29 rows x 33 columns]
            國家      ID iso_code  洲名          日期  總確診數  新增確診數  七天移動平均新增確診數  \
date
2020-01-16  台灣  163987      TWN  亞洲  2020-01-16     0      0        0.000
2020-01-17  台灣  163988      TWN  亞洲  2020-01-17     0      0        0.000
2020-01-18  台灣  163989      TWN  亞洲  2020-01-18     0      0        0.000
2020-01-19  台灣  163990      TWN  亞洲  2020-01-19     0      0        0.000
2020-01-20  台灣  163991      TWN  亞洲  2020-01-20     0      0        0.000
2020-01-21  台灣  163992      TWN  亞洲  2020-01-21     0      0        0.000
2020-01-22  台灣  163993      TWN  亞洲  2020-01-22     1      0        0.000
2020-01-23  台灣  163994      TWN  亞洲  2020-01-23     1      0        0.000
2020-01-24  台灣  163995      TWN  亞洲  2020-01-24     3      2        0.000
2020-01-25  台灣  163996      TWN  亞洲  2020-01-25     3      0        0.000
2020-01-26  台灣  163997      TWN  亞洲  2020-01-26     4      1        0.000
2020-01-27  台灣  163998      TWN  亞洲  2020-01-27     5      1        0.000
2020-01-28  台灣  163999      TWN  亞洲  2020-01-28     8      3        1.000
2020-01-29  台灣  164000      TWN  亞洲  2020-01-29     8      0        1.000
2020-01-30  台灣  164001      TWN  亞洲  2020-01-30     9      1        1.143
2020-01-31  台灣  164002      TWN  亞洲  2020-01-31    10      1        1.000
2020-02-01  台灣  164003      TWN  亞洲  2020-02-01    10      0        1.000
2020-02-02  台灣  164004      TWN  亞洲  2020-02-02    10      0        0.857
2020-02-03  台灣  164005      TWN  亞洲  2020-02-03    10      0        0.714
2020-02-04  台灣  164006      TWN  亞洲  2020-02-04    11      1        0.429
2020-02-05  台灣  164007      TWN  亞洲  2020-02-05    11      0        0.429
2020-02-06  台灣  164008      TWN  亞洲  2020-02-06    16      5        1.000
2020-02-07  台灣  164009      TWN  亞洲  2020-02-07    16      0        0.857
2020-02-08  台灣  164010      TWN  亞洲  2020-02-08    17      1        1.000
2020-02-09  台灣  164011      TWN  亞洲  2020-02-09    18      1        1.143
2020-02-10  台灣  164012      TWN  亞洲  2020-02-10    18      0        1.143
2020-02-11  台灣  164013      TWN  亞洲  2020-02-11    18      0        1.000
2020-02-12  台灣  164014      TWN  亞洲  2020-02-12    18      0        1.000
2020-02-13  台灣  164015      TWN  亞洲  2020-02-13    18      0        0.286
2020-02-14  台灣  164016      TWN  亞洲  2020-02-14    18      0        0.286
2020-02-15  台灣  164017      TWN  亞洲  2020-02-15    18      0        0.143
2020-02-16  台灣  164018      TWN  亞洲  2020-02-16    20      2        0.286
2020-02-17  台灣  164019      TWN  亞洲  2020-02-17    22      2        0.571
2020-02-18  台灣  164020      TWN  亞洲  2020-02-18    22      0        0.571
2020-02-19  台灣  164021      TWN  亞洲  2020-02-19    23      1        0.714
2020-02-20  台灣  164022      TWN  亞洲  2020-02-20    24      1        0.857
2020-02-21  台灣  164023      TWN  亞洲  2020-02-21    26      2        1.143
2020-02-22  台灣  164024      TWN  亞洲  2020-02-22    26      0        1.143
2020-02-23  台灣  164025      TWN  亞洲  2020-02-23    28      2        1.143
2020-02-24  台灣  164026      TWN  亞洲  2020-02-24    30      2        1.143
2020-02-25  台灣  164027      TWN  亞洲  2020-02-25    31      1        1.286
2020-02-26  台灣  164028      TWN  亞洲  2020-02-26    32      1        1.286
2020-02-27  台灣  164029      TWN  亞洲  2020-02-27    32      0        1.143
2020-02-28  台灣  164030      TWN  亞洲  2020-02-28    34      2        1.143
2020-02-29  台灣  164031      TWN  亞洲  2020-02-29    39      5        1.857

            總死亡數  新增死亡數  ...  七天移動平均疫苗新增接種劑數  每百人接種疫苗劑數  每百人接種疫苗人數  疫情控管指數  \
date                     ...
2020-01-16     0      0  ...             0.0        0.0        0.0    8.33
2020-01-17     0      0  ...             0.0        0.0        0.0    8.33
2020-01-18     0      0  ...             0.0        0.0        0.0    8.33
2020-01-19     0      0  ...             0.0        0.0        0.0    8.33
2020-01-20     0      0  ...             0.0        0.0        0.0   13.89
2020-01-21     0      0  ...             0.0        0.0        0.0   13.89
2020-01-22     0      0  ...             0.0        0.0        0.0   13.89
2020-01-23     0      0  ...             0.0        0.0        0.0   19.44
2020-01-24     0      0  ...             0.0        0.0        0.0   19.44
2020-01-25     0      0  ...             0.0        0.0        0.0   19.44
2020-01-26     0      0  ...             0.0        0.0        0.0   19.44
2020-01-27     0      0  ...             0.0        0.0        0.0   19.44
2020-01-28     0      0  ...             0.0        0.0        0.0   19.44
2020-01-29     0      0  ...             0.0        0.0        0.0   19.44
2020-01-30     0      0  ...             0.0        0.0        0.0   19.44
2020-01-31     0      0  ...             0.0        0.0        0.0   19.44
2020-02-01     0      0  ...             0.0        0.0        0.0   19.44
2020-02-02     0      0  ...             0.0        0.0        0.0   30.56
2020-02-03     0      0  ...             0.0        0.0        0.0   30.56
2020-02-04     0      0  ...             0.0        0.0        0.0   30.56
2020-02-05     0      0  ...             0.0        0.0        0.0   30.56
2020-02-06     0      0  ...             0.0        0.0        0.0   30.56
2020-02-07     0      0  ...             0.0        0.0        0.0   30.56
2020-02-08     0      0  ...             0.0        0.0        0.0   30.56
2020-02-09     0      0  ...             0.0        0.0        0.0   30.56
2020-02-10     0      0  ...             0.0        0.0        0.0   30.56
2020-02-11     0      0  ...             0.0        0.0        0.0   30.56
2020-02-12     0      0  ...             0.0        0.0        0.0   30.56
2020-02-13     0      0  ...             0.0        0.0        0.0   30.56
2020-02-14     0      0  ...             0.0        0.0        0.0   30.56
2020-02-15     0      0  ...             0.0        0.0        0.0   30.56
2020-02-16     1      1  ...             0.0        0.0        0.0   30.56
2020-02-17     1      0  ...             0.0        0.0        0.0   30.56
2020-02-18     1      0  ...             0.0        0.0        0.0   30.56
2020-02-19     1      0  ...             0.0        0.0        0.0   30.56
2020-02-20     1      0  ...             0.0        0.0        0.0   30.56
2020-02-21     1      0  ...             0.0        0.0        0.0   30.56
2020-02-22     1      0  ...             0.0        0.0        0.0   30.56
2020-02-23     1      0  ...             0.0        0.0        0.0   30.56
2020-02-24     1      0  ...             0.0        0.0        0.0   30.56
2020-02-25     1      0  ...             0.0        0.0        0.0   23.15
2020-02-26     1      0  ...             0.0        0.0        0.0   23.15
2020-02-27     1      0  ...             0.0        0.0        0.0   23.15
2020-02-28     1      0  ...             0.0        0.0        0.0   23.15
2020-02-29     1      0  ...             0.0        0.0        0.0   23.15

                總人口數  中位數年紀  70歲以上人口比例   平均壽命  解除隔離數      解封指數
date
2020-01-16  23855008   42.2      8.353  80.46      0  99999.00
2020-01-17  23855008   42.2      8.353  80.46      0  99999.00
2020-01-18  23855008   42.2      8.353  80.46      0  99999.00
2020-01-19  23855008   42.2      8.353  80.46      0  99999.00
2020-01-20  23855008   42.2      8.353  80.46      0  99999.00
2020-01-21  23855008   42.2      8.353  80.46      0  99999.00
2020-01-22  23855008   42.2      8.353  80.46      0  99999.00
2020-01-23  23855008   42.2      8.353  80.46      0  99999.00
2020-01-24  23855008   42.2      8.353  80.46      0  99999.00
2020-01-25  23855008   42.2      8.353  80.46      0  99999.00
2020-01-26  23855008   42.2      8.353  80.46      0  99999.00
2020-01-27  23855008   42.2      8.353  80.46      0  99999.00
2020-01-28  23855008   42.2      8.353  80.46      0  99999.00
2020-01-29  23855008   42.2      8.353  80.46      0  99999.00
2020-01-30  23855008   42.2      8.353  80.46      0  99999.00
2020-01-31  23855008   42.2      8.353  80.46      0  99999.00
2020-02-01  23855008   42.2      8.353  80.46      0  99999.00
2020-02-02  23855008   42.2      8.353  80.46      0  99999.00
2020-02-03  23855008   42.2      8.353  80.46      0  99999.00
2020-02-04  23855008   42.2      8.353  80.46      0  99999.00
2020-02-05  23855008   42.2      8.353  80.46      0  99999.00
2020-02-06  23855008   42.2      8.353  80.46      1  99999.00
2020-02-07  23855008   42.2      8.353  80.46      1  99999.00
2020-02-08  23855008   42.2      8.353  80.46      1  99999.00
2020-02-09  23855008   42.2      8.353  80.46      1  99999.00
2020-02-10  23855008   42.2      8.353  80.46      1  99999.00
2020-02-11  23855008   42.2      8.353  80.46      1  99999.00
2020-02-12  23855008   42.2      8.353  80.46      1  99999.00
2020-02-13  23855008   42.2      8.353  80.46      1  99999.00
2020-02-14  23855008   42.2      8.353  80.46      2  99999.00
2020-02-15  23855008   42.2      8.353  80.46      2  99999.00
2020-02-16  23855008   42.2      8.353  80.46      2      9.53
2020-02-17  23855008   42.2      8.353  80.46      2     10.52
2020-02-18  23855008   42.2      8.353  80.46      2     10.52
2020-02-19  23855008   42.2      8.353  80.46      2     11.02
2020-02-20  23855008   42.2      8.353  80.46      2     11.52
2020-02-21  23855008   42.2      8.353  80.46      2     12.52
2020-02-22  23855008   42.2      8.353  80.46      2     12.52
2020-02-23  23855008   42.2      8.353  80.46      2     13.52
2020-02-24  23855008   42.2      8.353  80.46      5      5.21
2020-02-25  23855008   42.2      8.353  80.46      5      5.41
2020-02-26  23855008   42.2      8.353  80.46      5      5.61
2020-02-27  23855008   42.2      8.353  80.46      5      5.61
2020-02-28  23855008   42.2      8.353  80.46      6      4.84
2020-02-29  23855008   42.2      8.353  80.46      9      3.45

[45 rows x 33 columns]